role_fitness_language_level_refinement_alternatives = [
    # arguments: GPT_role, user_role, language_level, cefr_description
    "Rephrase the sentence with 2 goals: 1. The sentence should use tone and voice of {0} speaking to {1}, 2. The sentence should only use {2} level of language proficiency, defined as {3}: ",
    
    # CoT, first level, then role
    # arguments: GPT_role, user_role, language_level, cefr_description
    "Rephrase the sentence with 2 goals: 1. The sentence should use tone and voice of {0} speaking to {1}, 2. The sentence should only use {2} level of language proficiency, defined as {3}.\nExamples:\n\nSentence:I can't give you that drink because we don't have it.\nTask:The sentence should only use C2 level of language.\nThought: Is this C2 level of language? If not, rephrase it to be C2 level.\nTask: The sentence should use tone and voice of a waiter talking to a customer.\nThought: Does it fit the role of a waiter? If not, rephrase it to fit the role.\nRefinement:I am very sorry, but we do not serve that drink, would you fancy a cocktail instead? Our bartenders make exquisit cocktails.\n\nSentence:Mother, I wish to go home.\nTask:The sentence should only use A2 level of language proficiency\nThought:Is the sentence on A2 level of language? If not, rephrase it to be A2.\nTask:The sentence should use tone and voice of a child speaking to its mother.\nThought: Does it match the role of a small child? If not rephrase it to match the role.\nRefinement:Mommy, I wanna go homee!.\n\n Return ONLY refinement.\n\nSentence: ",

    # Cot, first role, then level
    # arguments: language_leve, cefr_description, GPT_role, user_role
    "Rephrase the sentence with 2 goals: 1. The sentence should only use {2} level of language proficiency, defined as {3}.  2. The sentence should use tone and voice of {0} speaking to {1}.\nExamples:\n\nSentence:I can't give you that drink because we don't have it.\nTask: The sentence should use tone and voice of a waiter talking to a customer.\nThought: Does it fit the role of a waiter? If not, rephrase it to fit the role.\nTask:The sentence should only use C2 level of language.\nIs this C2 level of language? If not, rephrase it to be C2 level.\nRefinement:I am very sorry, but we do not serve that drink, would you fancy a cocktail instead? Our bartenders make exquisit cocktails.\n\nSentence:Mother, I wish to go home.\nTask:The sentence should use tone and voice of a child speaking to its mother.\nThought: Does it match the role of a small child? If not rephrase it to match the role.\nTask:The sentence should only use A2 level of language proficiency.\nThought: Is the sentence on A2 level of language? If not, rephrase it to be A2.\nRefinement:Mommy, I wanna go homee!.\n\n Return ONLY refinement.\n\nSentence:",

]